HelloPlayer/HelloPlayerMVC/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HelloPlayerMVC.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;

namespace HelloPlayerMVC.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        //private ApplicationDbContext db = new ApplicationDbContext();
        private ApplicationUserManager userManager;
        // GET: Admin
        public ActionResult Index()
        {
            //return View(db.ApplicationUsers.ToList());
            userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            return View(userManager.Users.OrderBy(n => n.FamilyName).ToList());
        }

        // GET: Admin/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //ApplicationUser applicationUser = db.ApplicationUsers.Find(id);
            userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            ApplicationUser applicationUser = userManager.FindById(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            var playerMgr = new Logic.PlayerManager();

            ViewBag.Status = userManager.GetRoles(id).First().ToString();
            return View(applicationUser);
        }

        public ActionResult UpgradeToPremium(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            userManager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            string roleFree = "Free Account";
            string rolePremium = "Premium Account";
            ApplicationUser applicationUser = userManager.FindById(id);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            int playerID = (int)applicationUser.PlayerID;
            var playerMgr = new Logic.PlayerManager();
            var premium = playerMgr.UpgradeToPremium(playerID);
            var addRole = userManager.AddToRole(id, rolePremium);
            var removeRole = userManager.RemoveFromRole(id, roleFree);
            return RedirectToAction("Details", new { id = id });
        }
    }
}

HelloPlayer/HelloPlayerMVC/Controllers/PatchNoteController.cs
using DataObject;
using Logic;
using LogicInterfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class PatchNoteController : Controller
    {
        IPatchNoteManager _patchNoteManager = new PatchNoteManager();
        // GET: PatchNote
        public ActionResult Index()
        {
            PatchNote _patchNotes = _patchNoteManager.RetrieveMostRecentPatchNotes();
            return View(_patchNotes);
        }

        public ActionResult PatchLines(string patchNoteID)
        {
            
            return View();
        }
    }
}

HelloPlayer/HelloPlayerMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Hello Player</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Hello Player", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Our Mission", "About", "Home")</li>
                    @if (User.IsInRole("Free Account") || User.IsInRole("Premium Account"))
                    {
                        <li>@Html.ActionLink("Quest", "Index", "Quest")</li>
                    }
                    @if (User.IsInRole("Administrator"))
                    {
                        <li>@Html.ActionLink("Player Administration", "Index", "Admin")</li>
                    }
                    <li>@Html.ActionLink("Patch Notes", "Index", "PatchNote")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Hello Player</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>